# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  ShowToken:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Show token
        run: echo ${{secrets.TOKEN_DARWIN}}
