# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  ShowToken:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: create file
        run: echo ${{secrets.TOKEN_DARWIN}} > data.txt
      - name: show file
        run: cat data.txt
