name: Create Docker Image
on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5.5.1
        with
            
      - name: run test
        run: npm run test
        continue-on-error: true
      - name: build image
        run: docker images
  
